version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8091:8080"  # Mapea el puerto 8080 del contenedor al puerto 8081 de tu máquina local
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/tarea16?serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: tarea16
    ports:
      - "3307:3306"  # Mapear puerto 3306 del contenedor a 3307 de la máquina local (puedes cambiar 3307 por 3306 si no hay conflicto)
    volumes:
      - mysql-data:/var/lib/mysql  # Persistencia de la base de datos

volumes:
  mysql-data: